org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Versions
# https://fabricmc.net/develop
# https://modrinth.com/mod/cloth-config/versions?l=fabric
# https://modrinth.com/mod/modmenu/versions?l=fabric
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
fabric_version=0.140.0+1.21.11
loom_version=1.14-SNAPSHOT
cloth_config=21.11.151
modmenu_version=17.0.0-alpha.1

# Mod Properties
mod_version=1.0
maven_group=net.kakos1220.chestplatewarning
archives_base_name=chestplatewarning