org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Versions
# https://fabricmc.net/develop
# https://modrinth.com/mod/cloth-config/versions?l=fabric
# https://modrinth.com/mod/modmenu/versions?l=fabric
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2
fabric_version=0.134.0+1.21.9
loom_version=1.11-SNAPSHOT
cloth_config=20.0.148
mod_menu=16.0.0-rc.1

# Mod Properties
mod_version=1.0
maven_group=net.kakos1220.chestplatewarning
archives_base_name=chestplatewarning