org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Versions
# https://fabricmc.net/develop
# https://modrinth.com/mod/cloth-config/versions?l=fabric
# https://modrinth.com/mod/modmenu/versions?l=fabric
minecraft_version=26.1
loader_version=0.18.5
fabric_version=0.145.1+26.1
loom_version=1.15-SNAPSHOT
cloth_config=26.1.154
modmenu_version=18.0.0-alpha.8

# Mod Properties
mod_version=1.0
maven_group=net.kakos1220.chestplatewarning
archives_base_name=chestplatewarning